version: 1.1.1
workflows:
    - subclass: WDL
      primaryDescriptorPath: /vcfToGds.wdl
      testParameterFiles:
          - /vcf-to-gds-local.json
      readMePath: 
          - /README.md
      authors:
          - name: Phuwanat
            email: s.phuwanat@gmail.com
      
